"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['pdf_splitter.py']
DATA_FILES = []
PLIST = {
    'LSPrefersPPC':True,
    'NSHumanReadableCopyright': "Copyright © 2023 Ryosuke Tanida. All rights reserved.",
    'CFBundleShortVersionString': '0.0.1',
    }
OPTIONS =  {'iconfile': 'icon.icns', 'plist':PLIST}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
